# Generated by Django 5.1 on 2024-08-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'Can view CustomUser'), ('can_create', 'Can create CustomUser'), ('can_edit', 'Can edit CustomUser'), ('can_delete', 'Can delete CustomUser')]},
        ),
    ]
